"""Made course searchable

Revision ID: 0f86bb711623
Revises: 4d3c66cf3600
Create Date: 2021-11-18 00:42:47.570991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f86bb711623'
down_revision = '4d3c66cf3600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smart_prerequisite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smart_prerequisite',
    sa.Column('course', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prereq', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course'], ['course.code'], name='fk_course_ref_course'),
    sa.ForeignKeyConstraint(['prereq'], ['course.code'], name='fk_prereq_ref_course'),
    sa.PrimaryKeyConstraint('course', 'prereq', name='primary')
    )
    # ### end Alembic commands ###
